### ISSUE TITLE
中文语料

### ISSUE THREAD

**Issue by tfzxyinhao** [alibaba/esim-response-selection#1]
有中文语料吗,语料格式是怎么样的?

**Comment by lukecq1231** [comment]
你可以试试E-commerce中文语料，格式是一致的。下载地址https://github.com/cooelf/DeepUtteranceAggregation

**Comment by tfzxyinhao** [comment]
跑这个脚本有什么推荐机器配置吗(GPU,CPU)?

**Comment by lukecq1231** [comment]
我有用过M40, P100, V100来跑。如果你的GPU显存不够，可以把batch size调小一些。CPU没有太多要求。

**Comment by VEDATTtc** [comment]
Loo

**Comment by vcbeaut** [comment]
@lukecq1231 @tfzxyinhao 大牛，问个问题，我看了下ubuntu语料，好多奇怪字符，语句不通，单词还是错的。这什么情况？

**Comment by lukecq1231** [comment]
@2191265529 这是正常的，ubuntu语料来源于论坛，本身就有很多低频词和typos，还有些错误可能是文本清洗时遗留的错误。

**Comment by vcbeaut** [comment]
@lukecq1231 那这么错误不会影响模型训练吗？

**Comment by lukecq1231** [comment]
@2191265529 不太会影响，你可以把这个看成是有噪声的语料。当然你可以做一些normalization，但我不确定能有多少提升。
