### ISSUE TITLE
请问一下：开源出的代码是否还采用了一些别的优化方法？另外也想问下如何应用？

### ISSUE THREAD

**Issue by muzier** [alibaba/esim-response-selection#11]
如题，按照Readme跑出来的MAP和MRR都只有0.33左右，而且跑到epoch5就结束了，论文上的准确率是不是还采用了其他的优化方法啊？另外同另一个issue一样，也想问下能否开源一下应用的代码？想试试看实际效果如何。。。
先谢过啦！
![esim_result](https://user-images.githubusercontent.com/11387287/63514262-d1ba9b80-c51a-11e9-862e-50d9b6b35c1f.jpg)

**Comment by lukecq1231** [comment]
我们没有采用论文之外其他的优化方法。能分享下你的配置参数吗？
另外，我们暂时没有开源应用代码的计划。
