### ISSUE TITLE
context = ' __eou__ __eot__ '.join(arr[1:-1]) + ' __eou__ __eot__ '

### ISSUE THREAD

**Issue by littttttlebird** [alibaba/esim-response-selection#12]
在data prepare 模块，为什么用两个符号“__eou__ __eot__"分割一个utterance而不是更简单的符号比如”__eou__"？
论文里面说，"The multi-turn context was concatenated and two special tokens, eou and eot , were inserted, where eou denotes end-of utterance and eot denotes end-of-turn."
所以这里的turn时什么意思？是一问一答2个utterance的意思吗？
如果是的话，一个context就应该是这样的，在偶数句后面多一个__eot__：
A1 __eou__ B1 __eou__ __eot__ A2 __eou__ B2 __eou__ __eot__ A3 __eou__
希望作者帮忙解答一下，谢谢

**Comment by lukecq1231** [comment]
这里引入eou eot两个符号是为了处理同一个speaker说多个utterance的情况，比如 A1 A2 B1 A3 B2这种，加上eou eot后就是A1 eou A2 eou eot B1 eou eot A3 eou eot B2 eou eot，这里的turn指的是一个speaker的一轮。当然，对于ubuntu这个数据集，每个speaker一轮都只有一个utterance，这里也可以只使用一个符号。

**Comment by littttttlebird** [comment]
OK，这么解释turn的话就明白了，谢谢
