### ISSUE TITLE
数据预处理部分

### ISSUE THREAD

**Issue by littttttlebird** [alibaba/esim-response-selection#13]
在textIterator里面，下面这段代码写的有问题吧，按照注释，应该是按照context和response长度和排序，这里怎么写成了“current_length = ins[1] + ins[2]”，应该是"current_length = len(ins[1]) + len(ins[2])"吧

                # sort by length of sum of target buffer and target_buffer
                length_list = []
                for ins in self.instance_buffer:
                    current_length = ins[1] + ins[2]
                    length_list.append(current_length)

                length_array = numpy.array(length_list)
                length_idx = length_array.argsort()

**Comment by lukecq1231** [comment]
@chuanhuayang 谢谢，这是一个bug，已修正。
