### ISSUE TITLE
训练和实际应用的偏差

### ISSUE THREAD

**Issue by littttttlebird** [alibaba/esim-response-selection#14]
训练数据中，负样本是随机采样得到的，会差的比较离谱，所以在训练时, p@1可以得到很高的值，因为差中选一比较容易。
但是实际应用中，一个query过来，类似检索策略给出的候选，质量会相对训练时随机采样的高很多，模型效果也就比较差了。
要怎么做才能消除这种训练和应用的偏差呢？

**Comment by lukecq1231** [comment]
我的建议是尽量使训练环境和测试环境类似。比如在这里，训练时也可以用类似检索策略来生成负样本。
