### ISSUE TITLE
model restore problem

### ISSUE THREAD

**Issue by Wind-Ward** [alibaba/esim-response-selection#15]
Hi,I have an perplexed issue when I try to restore the model to inference corpus.The issue is originated from the use of `tf.contrib.cudnn_rnn.CudnnLSTM`  to restore the model after using this function to train model.But there is no issue when I use the `tf.contrib.rnn.LSTMCell`  function to train corpus and restore model to inference corpus.I found that many developers encounter the same issue with me and no one can handle this issue correctly.I read your code,you just restore it by using the `saver.restore(sess, os.path.join(FLAGS.output_dir, "model_epoch_{}...)`,but I can't restore the model by using it.
![image](https://user-images.githubusercontent.com/28478688/65612466-e50fc980-dfe6-11e9-9a33-80fb15c90368.png)
Please help me to figure the issue out,thank you!My tensorflow's version is 1.10.0.

**Comment by lukecq1231** [comment]
CudnnLSTM restore模型确实要麻烦一些。你可以试试saver.restore来导入模型。一种简单的方法是设定max_train_epochs=0来跳过main.py中训练步骤，并指定best_epoch_num。代码756行左右的# evaluation process 后有导入模型并predict的参考。类似的issue你可以参考 https://github.com/alibaba/esim-response-selection/issues/3
