### ISSUE TITLE
最后一步训练时报错：

### ISSUE THREAD

**Issue by kyle-liao** [alibaba/esim-response-selection#2]
tensorflow.python.framework.errors_impl.UnknownError: Fail to find the dnn implementation.

**Comment by lukecq1231** [comment]
可能是cudnn的安装问题，你可以试试在run.sh中加入--use_cudnn=False，不过速度会慢会一些。

**Comment by kyle-liao** [comment]
非常感谢你的帮助，我刚刚找到问题所在了。不是我的cudnn安装问题，而是我tensorflow-gpu的版本为1.6.0，现在更新到1.9.0就能成功运行了。
