### ISSUE TITLE
模型怎么使用

### ISSUE THREAD

**Issue by kyle-liao** [alibaba/esim-response-selection#3]
请问训练后得到的模型，怎么使用。有一些简单demo吗？

**Comment by lukecq1231** [comment]
main.py里756行 # evaluation process后的代码就是模型训练后做测试的代码。你可以把max_train_epochs设为0，从而跳过训练部分，设定一下best_epoch_num，用predict_metrics函数就可以返回测试集/开发集的metrics以及每个样本正类的概率。

**Comment by kyle-liao** [comment]
我只跑了两轮，将定义为best_epoch_num = 1，输出的INFO:tensorflow:seen samples 10000
INFO:tensorflow:test set: MAP 0.6273972222222223 MRR 0.6273972222222223 Precision@1 0.447 Recall@1 0.447 Recall@2 0.635 Recall@5 0.89

请问，怎么才能输出对话的结果呢？

**Comment by lukecq1231** [comment]
你把predict_metrics函数返回的test_scores或valid_scores print出来，这些值就是每个样本的正类概率。

**Comment by kyle-liao** [comment]
那么请问，我怎么输入一句话然后返回我一句话呢？

**Comment by lukecq1231** [comment]
Ubuntu的数据集是输入一个多轮的context，模型给对应的100个候选答复打分，然后你根据打分排序，选出最高的正类概率的样本，作为返回的答复。如果你要输入一句话，返回一句话。你首先要有一个候选集合，把输入的一句话和候选集合中的每句话用ESIM模型打分，然后排序选出最高分的一句话就行。

**Comment by kyle-liao** [comment]
你好，我使用的是您提供的中文语料。test集在predict_metrics函数输出了test_scores的长度为10000,刚好对应了文本。请问，我怎么才能得到候选答复打分，这里我不是很明白。

**Comment by Saozy** [comment]
<p><s>您好，我用了你的模型和数据，跑了几个epoch以后得到了模型..</s></p> 
<p><s>我自己想加一个predict模块，重新导入模型的时候，</s></p>  
<p><s>saver = tf.train.import_meta_graph(modelpath + 'model_epoch_3.ckpt.meta')</s></p> 
<p><s>模型报错</s></p> 
<p><s>KeyError: "The name 'encoder/bilstm/cudnn_lstm/opaque_kernel_saveable' refers to an Operation not in the graph."</s></p> 
<p><s>换了保存的模型，epoch_0 到 epoch3 都不行</s></p> 
<p><s>...查了一下午stackflow也没得到答案.. </s></p> 
<p><s>我的tf是1.12，python是3.6</s></p> 
<p><s>能麻烦您帮我看一下吗</s></p> 
<p><s>是因为name的问题吗，我查了log，log里的变量名字是</s></p> <p><s>encoder/bilstm/cudnn_lstm/opaque_kernel</s></p> 

<p><s>problem solved 不导入模型直接restore变量..打扰了</s></p>
第二天还是会有问题...继续求解导入模型的问题

**Comment by lukecq1231** [comment]
@Saozy 你可以试试saver.restore来导入模型。一种简单的方法是设定max_train_epochs=0来跳过main.py中训练步骤，并指定best_epoch_num。代码756行# evaluation process 后有导入模型并predict的参考。

**Comment by Saozy** [comment]
@lukecq1231  谢谢回复  我确实也是这样做的
