### ISSUE TITLE
Sentence-encoding based methods implement

### ISSUE THREAD

**Issue by huangxianliang** [alibaba/esim-response-selection#5]
Sentence-encoding based methods useed in subtask 2 in the paper，where is the implement

**Comment by lukecq1231** [comment]
We don't have plan to release this part of the code currently. You could find the sentence-encoding code at:  https://github.com/ExplorerFreda/Structured-Self-Attentive-Sentence-Embedding  (Pytorch), https://github.com/flrngel/Self-Attentive-tensorflow  (Tensorflow)
