### ISSUE TITLE
dataset files can not download

### ISSUE THREAD

**Issue by 18611196340** [alibaba/esim-response-selection#7]
the link or file has been removed? I'm internet  in Chinese mainland, i can't download the link https://www.dropbox.com/s/2fdn26rj6h9bpvl/ubuntu_data.zip?dl=0 which write in the README.md file.

**Comment by lukecq1231** [comment]
The file has not been removed yet. It may be due to network problems. You could ask for dataset from (Xu et al, 2017) if you like.

**Comment by 18611196340** [comment]
Thank you very much，I am in the wall，哈哈
