### ISSUE TITLE
语料中的content为啥混在一起了？

### ISSUE THREAD

**Issue by 1148270327** [alibaba/esim-response-selection#8]
感谢阿里作者的无私奉献和共享。我看完语料后有些疑问，例如中文语料E-conmerce中的一行：
![image](https://user-images.githubusercontent.com/22876908/63071395-b87d8200-bf51-11e9-9ef1-5274f2f0a02b.png)
聊天内容被混在一起了，只有前两句和后两句用了tab键分开，中间的对话都没切分，混在了一起。
请问大佬，这是怎么回事呀？没理解

**Comment by lukecq1231** [comment]
数据中间应该也是有Tab的，只是显示不明显。见下图高亮Tab部分
![image](https://user-images.githubusercontent.com/12290570/63147292-36b05600-c030-11e9-93de-aa7ece7c1477.png)
